### ISSUE TITLE
Entries should show domains/categories by default

### ISSUE THREAD

**Issue by fcbond** [jmccrae/wordnet-angular#11]
E.g., the entry for _prick_ should show:
(n) _cock, prick, dick, shaft, pecker, tool, putz_ obscene terms for penis ⟪obscenity⟫⟨sexual activity⟩

assuming it is linked to ewn-07139048-n _obscenity_ by `exemplifies` and ewn-00845915-n _sexual-activity_ by `domain_topic`.    I think we should also show `domain_region`, ...

I like to show different links with different brackets, taking a lead from Japanese lexicographic practice, but I think the most important thing is to show them.

See the [taboo wordnet paper ](https://aclanthology.org/2021.gwc-1.5/) for more discussion.

**Comment by jmccrae** [comment]
Yes, this makes sense. We could probably also do `domain_region` as this often shows which dialect it is.

I would have to test this a bit to see that the information presentation is always clear however.
