### ISSUE TITLE
wordnet-rdf.princeton.edu is down

### ISSUE THREAD

**Issue by AndreiNesterov** [jmccrae/wordnet-angular#17]
Dear John,

http://wordnet-rdf.princeton.edu/ has not been accessible for several weeks now. Could you please let me know if it is gonna be fixed? Is there another way to access RDF-version of Princeton WordNet 3.1?

Kind regards,
Andrei

**Comment by arademaker** [comment]
This repo is about the code of the web interface, not sure if it is the right place for question about the data. 

Anyway, I do have another RDF version of Princeton Wordnet 3.0 at 

https://github.com/own-pt/openWordnet-PT
