### ISSUE TITLE
Click on `/id/***` not work

### ISSUE THREAD

**Issue by aclueless** [jmccrae/wordnet-angular#19]
Step to produce:
1. Visit https://en-word.net/lemma/cloudy
2. When the page fully loaded, click on `((meteorology))`

What happened?
The address bar changed to `https://en-word.net/id/oewn-06128170-n/`, and just that.

Expected behavior
The page content should be updated after/before the address changed.

More information
Right-click the link and the open in a new tab works correctly.

**Comment by jmccrae** [comment]
I don't really understand this bug. I have "fixed" it by forcing the link to open in a new tab. Possibly this may be fixed by updating the Angular version
